# Generated by Django 3.0.6 on 2020-05-25 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Env_Register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envlist_new',
            name='Release',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
